#!/bin/bash

#This script has been developed to clean single-end RNA-seq reads, so they can be assembled. The pipeline proceeds thus:
#1. Revmove adapters with bbduk.sh
#2. Check read quality with FastQC
#3. If reads FAIL, then trim with Trimmomatic with conservative parameters
#4. Error-correct reads and remvoe uncorrectable reads with tadpole.sh
#5. Decontaminate reads by filtering out reads that align to an index of rRNA, mitochondrial, and chloroplast sequences
#6. (Optionally) The clean reads can be assembled, just uncommment the call to the Trinity assembly function

#$1 = a file, where each line is the path to single-end reads
#$2 = the directory to send

Fastqc ()
{

	fastqc $1 --outdir=TrimmedQC_Zip	
	unzip ~/TrimmedQC_Zip/*.zip -d ~/TrimmedQC_Final
	rm ~/TrimmedQC_Zip/*.zip
	rm ~/TrimmedQC_Zip/*.html
	fail=$(grep -P "FAIL.+Per base sequence quality" ~/TrimmedQC_Final/*fastqc/summary.txt)
	
}

Trimm ()
{
	java -jar $Trimm SE $1 $2 SLIDINGWINDOW:4:15 MINLEN:36 1>$Out/trimmomatic.log 2>&1
}

Trin ()
{
	Trinity --seqType fq --max_memory 10G --single $1 --CPU 4 --output $2$Out$name.trinity --full_cleanup
}

Trimm="Programs/Trimmomatic-0.39/trimmomatic-0.39.jar"
BBduk="Programs/bbmap/bbduk.sh"
Tad="Programs/bbmap/tadpole.sh"
Bowtie2="Programs/bowtie2-2.4.1/bowtie2"
log="_log"
gz=".gz"
fail=""

while read line
do
	name=$(basename $line | cut -d. -f1-2)
	
	if [[ "$name" == *"Undetermined"* ]]
	then
		continue
	else

		Out=$name_assembly

		mkdir $Out

		#Only removes adapters from raw reads
		./$BBduk in=$line out=trimmed/$name ref=~/Programs/bbmap/resources/adapters.fa 2>$Out/bbduk.log
		
		#Quality check on adapter trimmed reads
		Fastqc trimmed/$name
		
		#If qualtiy check fails, trim with Trimmomatic
		if [[ ! -z "$fail" ]]
		then

                        Trimm $name trimmed/
		fi
		
		#Error-correct reads with Tadpole from BBmap suite of scripts
		#Tadpole will also remove uncorrectable reads
		$Tad in=trimmed/$name out=tadpoleCorrected/$name mode=correct tu threads=5 2>$Out/tadpole.log
		#perl Rcorrector/run_rcorrector.pl -s bbduk_trimmed/$name -t 4 -od rcorrected/

		#Decontaminate reads by aligning to an index of bacterial rRNA, chloropalst, and mitochondrial reference sequences
		#and retaining those that do not match
		$Bowtie2 --very-sensitive-local --un-gz $2$Out$name$gz -x criptContamBow/contam -U tadpoleCorrected/$name 1>/dev/null 2>$Out/bow.log

		#Trin $2$Out$name$gz

		./Script_Land/reset bbduk_trimmed
		./Script_Land/reset tadpoleCorrected
		./Script_Land/reset TrimmedQC_Zip
		./Script_Land/reset TrimmedQC_Final
	fi
done<$1
